import type { ThemeEntry } from './types.js'

const theme: ThemeEntry = {
  dark: {
    background: '#0a0a0a',
    foreground: '#eeeeee',
    card: '#141414',
    cardForeground: '#eeeeee',
    popover: '#1e1e1e',
    popoverForeground: '#eeeeee',
    primary: '#EC5B2B',
    primaryForeground: '#ffffff',
    secondary: '#EE7948',
    secondaryForeground: '#000000',
    muted: '#181818',
    mutedForeground: '#808080',
    accent: '#FFF7F1',
    accentForeground: '#000000',
    destructive: '#e06c75',
    destructiveForeground: '#000000',
    border: '#EC5B2B',
    input: '#3c3c3c',
    ring: '#EC5B2B',
    sidebar: '#141414',
    sidebarForeground: '#eeeeee',
    sidebarPrimary: '#EC5B2B',
    sidebarPrimaryForeground: '#ffffff',
    sidebarAccent: '#FFF7F1',
    sidebarAccentForeground: '#000000',
    sidebarBorder: '#EC5B2B',
    sidebarRing: '#EC5B2B',
    chart1: '#56b6c2',
    chart2: '#EC5B2B',
    chart3: '#6ba1e6',
    chart4: '#EC5B2B',
    chart5: '#EE7948',
  },
  light: {
    background: '#ffffff',
    foreground: '#1a1a1a',
    card: '#FFF7F1',
    cardForeground: '#1a1a1a',
    popover: '#f5f0eb',
    popoverForeground: '#1a1a1a',
    primary: '#EC5B2B',
    primaryForeground: '#ffffff',
    secondary: '#EE7948',
    secondaryForeground: '#000000',
    muted: '#f1f1f1',
    mutedForeground: '#8a8a8a',
    accent: '#c94d24',
    accentForeground: '#ffffff',
    destructive: '#d1383d',
    destructiveForeground: '#ffffff',
    border: '#EC5B2B',
    input: '#d4d4d4',
    ring: '#EC5B2B',
    sidebar: '#FFF7F1',
    sidebarForeground: '#1a1a1a',
    sidebarPrimary: '#EC5B2B',
    sidebarPrimaryForeground: '#ffffff',
    sidebarAccent: '#c94d24',
    sidebarAccentForeground: '#ffffff',
    sidebarBorder: '#EC5B2B',
    sidebarRing: '#EC5B2B',
    chart1: '#318795',
    chart2: '#EC5B2B',
    chart3: '#0062d1',
    chart4: '#EC5B2B',
    chart5: '#EE7948',
  },
}

export default theme
